"""
Django settings for world_cup project.
Generated by 'django-admin startproject' using Django 4.1.2 .
"""
import os
from datetime import timedelta
from pathlib import Path
from django.utils.translation import gettext_lazy as _
from corsheaders.defaults import default_headers

BASE_DIR = Path(__file__).resolve().parent.parent
DEBUG = int(os.getenv('DEBUG', default=True))
ALLOWED_HOSTS = ['*']  # os.getenv("ALLOWED_HOSTS", "127.0.0.1,0.0.0.0").split(",")

CSRF_TRUSTED_ORIGINS = os.getenv('CSRF_TRUSTED_ORIGINS', default='http://localhost,http://127.0.0.1').split(',')

# CORS #########################
CORS_ALLOW_ALL_ORIGINS= True
CORS_ORIGIN_WHITELIST =['127.0.0.1' ,'127.0.0.1:8000','79.175.131.40','79.175.131.40:8000','79.175.131.40:80']
#os.getenv("CORS_ORIGIN_WHITELIST", "http://127.0.0.1:8001").split(",")
#CORS_ORIGIN_ALLOW_ALL=True
CORS_ALLOW_CREDENTIALS=True
CORS_REPLACE_HTTPS_REFERER=True
CORS_ALLOW_HEADERS = [
#'*',
"X-ACCESS_TOKEN", "Access-Control-Allow-Origin", "Authorization", "Origin", "x-requested-with",
"Content-Type",
#"Content-Range", "Content-Disposition", "Content-Description"
'Access-Control-Request-Method',
#'Access-Control-Request-Headers',
'Access-Control-Allow-Origin',
#'Content-Type', 
'Access-Control-Allow-Headers', 'Authorization', 'X-Requested-With',
]
#CORS_ALLOW_HEADERS = default_headers + (
#    "access-control-allow-origin",
#)

CSRF_TRUSTED_ORIGINS = [
    'http://79.175.131.40',
]
CORS_ALLOWED_ORIGINS=[
    'http://79.175.131.40',
#    'http://79.175.131.40/Football1/', #?ut=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEyMzQ0NDc4OTAiLCJ1c2VybmFtZSI6InRlc3RBY2MyIn0.rHlDwOrBlDJARRDGEn8qAuGGNWW767pEdFRQ8cPG9cU',
#    'http://79.175.131.40/Football/', #?ut=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEyMzQ0NDc4OTAiLCJ1c2VybmFtZSI6InRlc3RBY2MyIn0.rHlDwOrBlDJARRDGEn8qAuGGNWW767pEdFRQ8cPG9cU',
    'http://79.175.131.40:8000',
    'http://localhost:8000',

]

CORS_ALLOW_METHODS = (
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
)

EVENTSTREAM_ALLOW_ORIGIN = "*"
EVENTSTREAM_ALLOW_CREDENTIALS = False
######################

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    "django_filters",
    "corsheaders",

    "django_redis",
    # "django_celery_results",
    # "django_celery_beat",

    'common',
    'user',
    'football.apps.FootballConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',

    'world_cup.mw.CorsPostCsrfMiddleware',
    'world_cup.mw.CorsMiddleware',
    'world_cup.mw.Fake2',

#    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTH_USER_MODEL = 'user.User'

ROOT_URLCONF = 'world_cup.urls'
PROJECT_NAME = os.getenv("PROJECT_NAME", ROOT_URLCONF.split(".")[0])

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'libraries': {
                'staticfiles': 'django.templatetags.static',
            },
        },
    }
]

WSGI_APPLICATION = 'world_cup.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.getenv('POSTGRES_DB', default=PROJECT_NAME),
        'USER': os.getenv('POSTGRES_USER', default='postgres'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD', default='12345'),
        'HOST': os.getenv('POSTGRES_HOST', default='localhost'),
        'PORT': int(os.getenv('POSTGRES_PORT', default='5432')),
    },

}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True
# STATIC_URL = '/static/'

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATICFILES_DIRS = [
    MEDIA_ROOT,
]
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SYSTEM_USER_NAME = os.getenv("SYSTEM_USER_NAME", 'SYSTEM')
SYSTEM_USER_MOBILE_NUMBER = os.getenv('SYSTEM_USER_MOBILE_NUMBER', default="09000000000")
SYSTEM_USER_EMAIL = os.getenv('SYSTEM_USER_EMAIL', default="system@system.com")
SYSTEM_USER_PASSWORD = os.getenv('SYSTEM_USER_PASSWORD', default="1234567890")

ROOT_USER_NAME = os.getenv("SYSTEM_USER_NAME", 'root')
ROOT_USER_MOBILE_NUMBER = os.getenv('SYSTEM_USER_MOBILE_NUMBER', default="08000000000")
ROOT_USER_EMAIL = os.getenv('SYSTEM_USER_EMAIL', default="root@system.com")
ROOT_USER_PASSWORD = os.getenv('ROOT_USER_PASSWORD', default="123456")

# Redis
CONFIGURATION_PREFIX = 'common_configuration'
CORRECT_PREDICTION_SCORE_PREFIX = 'common_CorrectPredictScore'

REST_FRAMEWORK = {
    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.NamespaceVersioning',
    'DEFAULT_VERSION': 'v1',
    'ALLOWED_VERSIONS': os.environ.get('REST_FRAMEWORK_ALLOWED_VERSIONS', default='v1').split(','),

    'DEFAULT_PAGINATION_CLASS': 'common.utils.pagination.ResponsePaginator',
    'PAGE_SIZE': int(os.getenv('PAGE_SIZE', 10)),

    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),

    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',

    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],

    'DEFAULT_THROTTLE_RATES': {
        'anon': os.getenv("ANON_THROTTLE_RATES", '1000/hour'),
        'user': os.getenv("USER_THROTTLE_RATES", '1000/hour')
    },

}
CACHE_EXPIRATION_PLAYER_TIME: int = int(os.getenv('CACHE_EXPIRATION_PLAYER_TIME', default=60))
CACHE_EXPIRATION_LEADERBOARD_TIME: int = int(os.getenv('CACHE_EXPIRATION_LEADERBOARD_TIME', default=60))
CACHE_EXPIRATION_OTP_TIME: int = int(os.getenv('CACHE_EXPIRATION_LEADERBOARD_TIME', default=60))

# Application
STAGE_SERVER = os.getenv("STAGE_SERVER", default='https://stage.myserver.ir')
SECRET_KEY = os.getenv('SECRET_KEY', default='sexcrsdet_key_rZe-AE9z1xb*o)n(SV-p4jyx0Sj-v$Jt+qx4bP!sw=')
VERSION = '0.1.0'
SITE_ID = 1
SITE_HEADER = _('World Cup Manager')
SITE_TITLE = _('Welcome to World Cup Manager')
WEB_PROTOCOL = os.environ.get('WEB_PROTOCOL', 'http')

# CELERY
BROKER_URL = os.getenv("BROKER_URL", default='redis://localhost:6379')
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", default='redis://localhost:6379')
CELERY_ACCEPT_CONTENT = ['application/json', 'application/x-python-serialize']
CELERY_TASK_SERIALIZER = 'pickle'
CELERY_RESULT_SERIALIZER = 'pickle'
CELERY_TIMEZONE = TIME_ZONE

# SMS
SMS_PANEL_API_KEY = os.environ.get('SMS_PANEL_API_KEY')
SEND_SMS_VERIFY = 'https://api.kavenegar.com/v1/{}/verify/lookup.json'.format(SMS_PANEL_API_KEY)
SEND_SMS_URL = 'https://api.kavenegar.com/v1/{}/sms/send.json'.format(SMS_PANEL_API_KEY)

# CORS
#CORS_ALLOW_ALL_ORIGINS= True
#CORS_ORIGIN_WHITELIST = os.getenv("CORS_ORIGIN_WHITELIST", "http://127.0.0.1:8001").split(",")
#CORS_ORIGIN_ALLOW_ALL=True
#CORS_ALLOW_HEADERS = [
#'*',
#'accept',
#'accept-encoding',
#'authorization',
#'content-type',
#'dnt',
#'origin',
#'user-agent',
#'x-csrftoken',
#'x-requested-with',
#'Access-Control-Allow-Origin',
#'Content-Type', 'Access-Control-Allow-Headers', 'Authorization', 'X-Requested-With',
#]

#CORS_ALLOW_METHODS = (
#    'DELETE',
#    'GET',
#    'OPTIONS',
#    'PATCH',
#    'POST',
#    'PUT',
#)
#CSRF_TRUSTED_ORIGINS = [
#    'http://79.175.131.40',
#]
#CORS_ALLOWED_ORIGINS=[
#    'http://79.175.131.40',
#    'http://79.175.131.40:3000',
#    "http://localhost:3000",

#]

#EVENTSTREAM_ALLOW_ORIGIN = "*"
#EVENTSTREAM_ALLOW_CREDENTIALS = False

####################
#from corsheaders.defaults import default_headers
#CORS_ORIGIN_ALLOW_ALL = True
#CORS_ALLOW_CREDENTIALS = False
#CORS_REPLACE_HTTPS_REFERER = True

#CORS_ALLOW_HEADERS = default_headers + (
#    'content-range',"access-control-allow-origin",
#)
#USE_X_FORWARDED_HOST = True
#USE_X_FORWARDED_PORT = True
#SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

