# Generated by Django 4.1.2 on 2022-10-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionarrange',
            name='is_penalty',
            field=models.BooleanField(default=False, verbose_name='is penalty'),
        ),
        migrations.AddField(
            model_name='predictionarrange',
            name='winner',
            field=models.IntegerField(choices=[(2, 'Team 1'), (0, 'Team 2'), (1, 'Draw')], default=1, verbose_name='winner'),
            preserve_default=False,
        ),
    ]
