# Generated by Django 4.0.8 on 2022-11-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionarrange',
            name='is_processed',
            field=models.BooleanField(default=False, help_text='after player predicts calculated change to True', verbose_name='is processed'),
        ),
    ]
