# Generated by Django 4.1.2 on 2022-10-25 06:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamplayer',
            name='number',
            field=models.PositiveBigIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='teamplayer',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.team', verbose_name='team'),
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('winner', models.IntegerField(choices=[(2, 'Team 1'), (0, 'Team 2'), (1, 'Draw')], verbose_name='winner')),
                ('is_penalty', models.BooleanField(default=False, verbose_name='is penalty')),
                ('team_1', models.JSONField(verbose_name='team 1')),
                ('team_2', models.JSONField(verbose_name='team 2')),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='football.match', verbose_name='match')),
            ],
            options={
                'verbose_name': 'Match Result',
                'verbose_name_plural': 'Match Results',
            },
        ),
    ]
