# Generated by Django 4.0.8 on 2022-11-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_matchresult_represent_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamplayer',
            name='role',
            field=models.IntegerField(choices=[(0, 'GK'), (1, 'LB'), (2, 'RB'), (3, 'LCB'), (4, 'RCB'), (5, 'CDM'), (6, 'LCM'), (7, 'RCM'), (8, 'RW'), (9, 'LW'), (10, 'ST')], default=0, verbose_name='role'),
        ),
    ]
